[project]
name = "fkperplexity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "browser-use>=0.6.1",
    "langgraph>=0.6.6",
    "pillow>=11.3.0",
    "transformers>=4.55.4",
]
